events.listen('player.logged_in', function (e) {

const start_book = Item.of('akashictome:tome', {RepairCost:0,display:{Name:"{\"text\":\"All The Magic Guide\"}"},"akashictome:data":{resourcefulbees:{id:"patchouli:guide_book",Count:1,tag:{"patchouli:book":"resourcefulbees:fifty_shades_of_bees"}},astralsorcery:{id:"astralsorcery:tome",Count:1},theoneprobe:{id:"theoneprobe:probenote",Count:1},psi:{id:"patchouli:guide_book",Count:1,tag:{"patchouli:book":"psi:encyclopaedia_psionica"}},"mana-and-artifice":{id:"mana-and-artifice:guide_book",Count:1},astral:{id:"patchouli:guide_book",Count:1,tag:{"patchouli:book":"astral:astronomicon"}},allthemodium:{id:"patchouli:guide_book",Count:1,tag:{"patchouli:book":"allthemodium:allthemodium"}},eidolon:{id:"eidolon:codex",Count:1},elementalcraft:{id:"patchouli:guide_book",Count:1,tag:{"patchouli:book":"elementalcraft:element_book"}},turtlemancy:{id:"patchouli:guide_book",Count:1,tag:{"patchouli:book":"turtlemancy:turtlenomicon"}},botania:{id:"botania:lexicon",Count:1,tag:{}},feywild:{id:"feywild:feywild_lexicon",Count:1},theurgy:{id:"theurgy:grimoire",Count:1},malum:{id:"malum:encyclopedia_arcana",Count:1},evilcraft:{id:"evilcraft:origins_of_darkness",Count:1},integratedtunnels:{id:"integrateddynamics:on_the_dynamics_of_integration",Count:1},enigmaticlegacy:{id:"enigmaticlegacy:the_acknowledgment",Count:1},theabyss:{id:"patchouli:guide_book",Count:1,tag:{"patchouli:book":"theabyss:abyssbookitem"}},naturesaura:{id:"patchouli:guide_book",Count:1,tag:{"patchouli:book":"naturesaura:book"}},pedestals:{id:"patchouli:guide_book",Count:1,tag:{"patchouli:book":"pedestals:manual"}},occultism:{id:"occultism:dictionary_of_spirits",Count:1},ars_nouveau:{id:"ars_nouveau:worn_notebook",Count:1},mysticalworld:{id:"mysticalworld:encyclopedia",Count:1},bloodmagic:{id:"patchouli:guide_book",Count:1,tag:{"patchouli:book":"bloodmagic:guide"}},twilightforest:{id:"patchouli:guide_book",Count:1,tag:{"patchouli:book":"twilightforest:guide"}},mysticalagriculture:{id:"patchouli:guide_book",Count:1,tag:{"patchouli:book":"mysticalagriculture:guide"}}}})

//Akashic Tome (with starting books)
e.player.give(start_book)
e.player.give('ftbquests:book')
})



onEvent('recipes', e => {

const start_book = Item.of('akashictome:tome', {RepairCost:0,display:{Name:"{\"text\":\"All The Magic Guide\"}"},"akashictome:data":{resourcefulbees:{id:"patchouli:guide_book",Count:1,tag:{"patchouli:book":"resourcefulbees:fifty_shades_of_bees"}},astralsorcery:{id:"astralsorcery:tome",Count:1},theoneprobe:{id:"theoneprobe:probenote",Count:1},psi:{id:"patchouli:guide_book",Count:1,tag:{"patchouli:book":"psi:encyclopaedia_psionica"}},"mana-and-artifice":{id:"mana-and-artifice:guide_book",Count:1},astral:{id:"patchouli:guide_book",Count:1,tag:{"patchouli:book":"astral:astronomicon"}},allthemodium:{id:"patchouli:guide_book",Count:1,tag:{"patchouli:book":"allthemodium:allthemodium"}},eidolon:{id:"eidolon:codex",Count:1},elementalcraft:{id:"patchouli:guide_book",Count:1,tag:{"patchouli:book":"elementalcraft:element_book"}},turtlemancy:{id:"patchouli:guide_book",Count:1,tag:{"patchouli:book":"turtlemancy:turtlenomicon"}},botania:{id:"botania:lexicon",Count:1,tag:{}},feywild:{id:"feywild:feywild_lexicon",Count:1},theurgy:{id:"theurgy:grimoire",Count:1},malum:{id:"malum:encyclopedia_arcana",Count:1},evilcraft:{id:"evilcraft:origins_of_darkness",Count:1},integratedtunnels:{id:"integrateddynamics:on_the_dynamics_of_integration",Count:1},enigmaticlegacy:{id:"enigmaticlegacy:the_acknowledgment",Count:1},theabyss:{id:"patchouli:guide_book",Count:1,tag:{"patchouli:book":"theabyss:abyssbookitem"}},naturesaura:{id:"patchouli:guide_book",Count:1,tag:{"patchouli:book":"naturesaura:book"}},pedestals:{id:"patchouli:guide_book",Count:1,tag:{"patchouli:book":"pedestals:manual"}},occultism:{id:"occultism:dictionary_of_spirits",Count:1},ars_nouveau:{id:"ars_nouveau:worn_notebook",Count:1},mysticalworld:{id:"mysticalworld:encyclopedia",Count:1},bloodmagic:{id:"patchouli:guide_book",Count:1,tag:{"patchouli:book":"bloodmagic:guide"}},twilightforest:{id:"patchouli:guide_book",Count:1,tag:{"patchouli:book":"twilightforest:guide"}},mysticalagriculture:{id:"patchouli:guide_book",Count:1,tag:{"patchouli:book":"mysticalagriculture:guide"}}}})

e.shapeless(start_book, ['minecraft:book', '#forge:string'])
})
