events.listen('player.logged_in', function (e) {

const start_book = Item.of('akashictome:tome', {RepairCost:0.0,"akashictome:data":{tconstruct:{id:"tconstruct:materials_and_you",Count:1.0},evilcraft:{id:"evilcraft:origins_of_darkness",Count:1.0},integratedtunnels:{id:"integrateddynamics:on_the_dynamics_of_integration",Count:1},resourcefulbees:{id:"patchouli:guide_book",Count:1.0,tag:{"patchouli:book":"resourcefulbees:fifty_shades_of_bees"}},astralsorcery:{id:"astralsorcery:tome",Count:1.0},theoneprobe:{id:"theoneprobe:probenote",Count:1.0},psi:{id:"patchouli:guide_book",Count:1.0,tag:{"patchouli:book":"psi:encyclopaedia_psionica"}},"mana-and-artifice":{id:"mana-and-artifice:guide_book",Count:1.0},theabyss:{id:"patchouli:guide_book",Count:1.0,tag:{"patchouli:book":"theabyss:abyssbookitem"}},naturesaura:{id:"patchouli:guide_book",Count:1.0,tag:{"patchouli:book":"naturesaura:book"}},astral:{id:"patchouli:guide_book",Count:1.0,tag:{"patchouli:book":"astral:astronomicon"}},allthemodium:{id:"patchouli:guide_book",Count:1.0,tag:{"patchouli:book":"allthemodium:allthemodium"}},pedestals:{id:"patchouli:guide_book",Count:1.0,tag:{"patchouli:book":"pedestals:manual"}},eidolon:{id:"eidolon:codex",Count:1},occultism:{id:"occultism:dictionary_of_spirits",Count:1.0},elementalcraft:{id:"patchouli:guide_book",Count:1.0,tag:{"patchouli:book":"elementalcraft:element_book"}},turtlemancy:{id:"patchouli:guide_book",Count:1.0,tag:{"patchouli:book":"turtlemancy:turtlenomicon"}},botania:{id:"botania:lexicon",Count:1.0,tag:{}},ars_nouveau:{id:"ars_nouveau:worn_notebook",Count:1.0},mysticalworld:{id:"mysticalworld:encyclopedia",Count:1.0},bloodmagic:{id:"patchouli:guide_book",Count:1.0,tag:{"patchouli:book":"bloodmagic:guide"}},twilightforest:{id:"patchouli:guide_book",Count:1.0,tag:{"patchouli:book":"twilightforest:guide"}},mysticalagriculture:{id:"patchouli:guide_book",Count:1.0,tag:{"patchouli:book":"mysticalagriculture:guide"}}},display:{Name:"{\"text\":\"All The Magic Guide\"}"}})

//Akashic Tome (with starting books)
e.player.give(start_book)
})

onEvent('recipes', e => {

const start_book = Item.of('akashictome:tome', {RepairCost:0.0,"akashictome:data":{tconstruct:{id:"tconstruct:materials_and_you",Count:1.0},evilcraft:{id:"evilcraft:origins_of_darkness",Count:1.0},integratedtunnels:{id:"integrateddynamics:on_the_dynamics_of_integration",Count:1},resourcefulbees:{id:"patchouli:guide_book",Count:1.0,tag:{"patchouli:book":"resourcefulbees:fifty_shades_of_bees"}},astralsorcery:{id:"astralsorcery:tome",Count:1.0},theoneprobe:{id:"theoneprobe:probenote",Count:1.0},psi:{id:"patchouli:guide_book",Count:1.0,tag:{"patchouli:book":"psi:encyclopaedia_psionica"}},"mana-and-artifice":{id:"mana-and-artifice:guide_book",Count:1.0},theabyss:{id:"patchouli:guide_book",Count:1.0,tag:{"patchouli:book":"theabyss:abyssbookitem"}},naturesaura:{id:"patchouli:guide_book",Count:1.0,tag:{"patchouli:book":"naturesaura:book"}},astral:{id:"patchouli:guide_book",Count:1.0,tag:{"patchouli:book":"astral:astronomicon"}},allthemodium:{id:"patchouli:guide_book",Count:1.0,tag:{"patchouli:book":"allthemodium:allthemodium"}},pedestals:{id:"patchouli:guide_book",Count:1.0,tag:{"patchouli:book":"pedestals:manual"}},eidolon:{id:"eidolon:codex",Count:1},occultism:{id:"occultism:dictionary_of_spirits",Count:1.0},elementalcraft:{id:"patchouli:guide_book",Count:1.0,tag:{"patchouli:book":"elementalcraft:element_book"}},turtlemancy:{id:"patchouli:guide_book",Count:1.0,tag:{"patchouli:book":"turtlemancy:turtlenomicon"}},botania:{id:"botania:lexicon",Count:1.0,tag:{}},ars_nouveau:{id:"ars_nouveau:worn_notebook",Count:1.0},mysticalworld:{id:"mysticalworld:encyclopedia",Count:1.0},bloodmagic:{id:"patchouli:guide_book",Count:1.0,tag:{"patchouli:book":"bloodmagic:guide"}},twilightforest:{id:"patchouli:guide_book",Count:1.0,tag:{"patchouli:book":"twilightforest:guide"}},mysticalagriculture:{id:"patchouli:guide_book",Count:1.0,tag:{"patchouli:book":"mysticalagriculture:guide"}}},display:{Name:"{\"text\":\"All The Magic Guide\"}"}})

e.shapeless(start_book, ['minecraft:book', '#forge:string'])
})
