
[Server]
	#Allow Player to Use Starting Tweaks
	allowStartingHealthTweaks = false
	#Set Starting Amount for Player to Start with (ALLOW STARTING HEALTH TWEAKS NEEDS TO BE TRUE)
	startingHealth = 20

