
[client]
	#Use the old Barakoa textures instead of the current ones
	old_barakoa_textures = false
	#Toggles the lantern glow effect, which may look bad with certain shaders
	glow_effect = true
	#Enable camera shaking during certain mob attacks and abilities.
	do_camera_shake = true

