
#Storage Settings
[storage]
	#The amount of slots the storage stabilizer tier 1 provides.
	stabilizerTier1Slots = 128
	#The amount of slots the storage stabilizer tier 3 provides.
	stabilizerTier3Slots = 512
	#The amount of slots the storage stabilizer tier 2 provides.
	stabilizerTier2Slots = 256
	#True to use the configured controllerStackSize for all items, instead of the stack sizes provided by item type (such as 16 for ender pearls, 64 for iron ingot). WARNING: Setting this to false may have a negative impact on performance.
	overrideItemStackSizes = true
	#The amount of slots the storage actuator provides.
	controllerBaseSlots = 128
	#The stack size the storage actuator uses.
	controllerStackSize = 1024
	#The amount of slots the storage stabilizer tier 4 provides.
	stabilizerTier4Slots = 1024

#Spirit Job Settings
[spirit_job]
	#The multiplier to each crushing recipe's crushing_time for Tier 1 Crusher Spirits.
	tier1CrusherTimeMultiplier = 2.0
	#Currently unused. The multiplier to each crushing recipe's crushing_time for Tier 4 Crusher Spirits.
	tier4CrusherTimeMultiplier = 0.2
	#The duration for the slow falling effect applied by a drikwing.
	drikwingFamiliarSlowFallingSeconds = 15
	#Currently unused. The multiplier to each crushing recipe's crushing_time for Tier 3 Crusher Spirits.
	tier3CrusherTimeMultiplier = 0.5
	#Currently unused. The multiplier to each crushing recipe's crushing_time for Tier 2 Crusher Spirits.
	tier2CrusherTimeMultiplier = 1.0

#Ritual Settings
[rituals]
	#Enables the ritual to start a thunderstorm.
	enableThunderWeatherRitual = true
	#Enables the ritual to set time to day.
	enableDayTimeRitual = true
	#Enables the ritual to set time to night.
	enableNightTimeRitual = true
	#Enables the ritual to start rainy weather.
	enableRainWeatherRitual = true
	#If enabled, rituals are interrupted if *more* ingredients are present than needed. This should usually be disabled, but can improve performance if (very very) many rituals are running.
	enableRemainingIngredientCountMatching = false
	#Enables the ritual to clear rainy weather.
	enableClearWeatherRitual = true

#Dimensional Mineshaft Settings
[dimensional_mineshaft]

	#Miner Spirit Settings
	[dimensional_mineshaft.miner_djinni_ores]
		#The amount of blocks the spirit will obtain per mining operation
		rollsPerOperation = 1
		#The amount of mining operations the spirit can perform before breaking.
		durability = 100
		#The amount of time it takes the spirit to perform one mining operation.
		maxMiningTime = 400

	#Miner Spirit Settings
	[dimensional_mineshaft.miner_foliot_unspecialized]
		#The amount of blocks the spirit will obtain per mining operation
		rollsPerOperation = 1
		#The amount of mining operations the spirit can perform before breaking.
		durability = 1000
		#The amount of time it takes the spirit to perform one mining operation.
		maxMiningTime = 400

