
[The_Nether]
	#
	#Is the list of biomes a blacklist or whitelist?
	#When this list is a blacklist, the values in the list will not be in world generation.
	#When this list is a whitelist, Adding a biome several times gives it more weight in generation and it must contain at least 1 value.
	#When set to true, datapack biomes will work automatically! When set to false, you will need to manually add datapack entries.
	#Default: true
	isBlacklistNether = true
	#
	#This works as a whitelist or blacklist depending on the "isBlacklistNether" value.
	#NO SPACES AFTER COMMAS!
	#Default: ""
	BlacklistNether = "byg:embur_bog,allthemodium:modified_gravelly_mountains,allthemodium:gravelly_mountains,allthemodium:mining,allthemodium:badlands,allthemodium:badlands_plateau,allthemodium:basalt_deltas,allthemodium:crimson_forest,allthemodium:desert,allthemodium:desert_hills,allthemodium:eroded_badlands,allthemodium:mining,allthemodium:modified_badlands_plateau,allthemodium:mountain_edge,allthemodium:mountains,allthemodium:nether_wastes,allthemodium:soul_sand_valley,allthemodium:the_other,allthemodium:warped_forest"

